import type { Product } from "@/db/schema";

// Mock products for development (before DB is set up)
export const mockProducts: Product[] = [
  {
    id: 1,
    name: "Apple iPhone 16",
    ticker: "AAPL",
    description: "The latest flagship smartphone from Apple",
    category: "Electronics",
    imageUrl: null,
    ownerId: 1,
    currentPrice: "8.75",
    previousPrice: "8.52",
    priceChange: "0.23",
    priceChangePercent: "2.70",
    totalRatings: 1247,
    status: "active",
    itemType: "product",
    isInNpbNsb: false,
    npbNsbExpiresAt: null,
    purchaseUrl: null,
    externalPageUrl: null,
    sentimentDiscount: "15% Off",
    sentimentDiscountCode: "PRODO15",
    brandName: "Apple",
    totalShares: "1000000.00",
    availableShares: "950000.00",
    initialSharePrice: "5.00",
    isAdflowPromoted: false,
    adflowExpiresAt: null,
    hasDividendBadge: true,
    dividendStreakDays: 45,
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date(),
  },
  {
    id: 2,
    name: "Tesla Model S",
    ticker: "TSLA",
    description: "Premium electric sedan with autopilot",
    category: "Automotive",
    imageUrl: null,
    ownerId: 1,
    currentPrice: "7.12",
    previousPrice: "7.45",
    priceChange: "-0.33",
    priceChangePercent: "-4.43",
    totalRatings: 892,
    status: "active",
    itemType: "product",
    isInNpbNsb: false,
    npbNsbExpiresAt: null,
    purchaseUrl: null,
    externalPageUrl: null,
    sentimentDiscount: null,
    sentimentDiscountCode: null,
    brandName: "Tesla",
    totalShares: "500000.00",
    availableShares: "480000.00",
    initialSharePrice: "5.00",
    isAdflowPromoted: false,
    adflowExpiresAt: null,
    hasDividendBadge: false,
    dividendStreakDays: 12,
    createdAt: new Date("2024-02-01"),
    updatedAt: new Date(),
  },
  {
    id: 3,
    name: "Nike Air Max",
    ticker: "NKE",
    description: "Iconic athletic footwear",
    category: "Fashion",
    imageUrl: null,
    ownerId: 1,
    currentPrice: "8.21",
    previousPrice: "8.15",
    priceChange: "0.06",
    priceChangePercent: "0.74",
    totalRatings: 2341,
    status: "active",
    itemType: "product",
    isInNpbNsb: true,
    npbNsbExpiresAt: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000),
    purchaseUrl: "https://nike.com",
    externalPageUrl: null,
    sentimentDiscount: "Free Shipping",
    sentimentDiscountCode: "NIKEFREE",
    brandName: "Nike",
    totalShares: "2000000.00",
    availableShares: "1800000.00",
    initialSharePrice: "5.00",
    isAdflowPromoted: true,
    adflowExpiresAt: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000),
    hasDividendBadge: true,
    dividendStreakDays: 67,
    createdAt: new Date("2023-11-20"),
    updatedAt: new Date(),
  },
  {
    id: 4,
    name: "Starbucks Pumpkin Latte",
    ticker: "SBUX",
    description: "Seasonal favorite beverage",
    category: "Food & Beverage",
    imageUrl: null,
    ownerId: 1,
    currentPrice: "6.89",
    previousPrice: "6.92",
    priceChange: "-0.03",
    priceChangePercent: "-0.43",
    totalRatings: 567,
    status: "active",
    itemType: "product",
    isInNpbNsb: false,
    npbNsbExpiresAt: null,
    purchaseUrl: null,
    externalPageUrl: null,
    sentimentDiscount: null,
    sentimentDiscountCode: null,
    brandName: "Starbucks",
    totalShares: "100000.00",
    availableShares: "100000.00",
    initialSharePrice: "5.00",
    isAdflowPromoted: false,
    adflowExpiresAt: null,
    hasDividendBadge: false,
    dividendStreakDays: 8,
    createdAt: new Date("2024-03-01"),
    updatedAt: new Date(),
  },
  {
    id: 5,
    name: "Sony PlayStation 5",
    ticker: "SNY",
    description: "Next-gen gaming console",
    category: "Gaming",
    imageUrl: null,
    ownerId: 1,
    currentPrice: "9.15",
    previousPrice: "8.98",
    priceChange: "0.17",
    priceChangePercent: "1.89",
    totalRatings: 3421,
    status: "active",
    itemType: "product",
    isInNpbNsb: false,
    npbNsbExpiresAt: null,
    purchaseUrl: null,
    externalPageUrl: null,
    sentimentDiscount: "10% PS Store",
    sentimentDiscountCode: "SONY10",
    brandName: "Sony",
    totalShares: "500000.00",
    availableShares: "100000.00",
    initialSharePrice: "5.00",
    isAdflowPromoted: false,
    adflowExpiresAt: null,
    hasDividendBadge: true,
    dividendStreakDays: 89,
    createdAt: new Date("2023-09-15"),
    updatedAt: new Date(),
  },
  {
    id: 6,
    name: "Dyson V15 Vacuum",
    ticker: "DYSN",
    description: "Premium cordless vacuum cleaner",
    category: "Home",
    imageUrl: null,
    ownerId: 1,
    currentPrice: "7.88",
    previousPrice: "7.65",
    priceChange: "0.23",
    priceChangePercent: "3.01",
    totalRatings: 445,
    status: "ipo",
    itemType: "product",
    isInNpbNsb: true,
    npbNsbExpiresAt: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000),
    purchaseUrl: null,
    externalPageUrl: null,
    sentimentDiscount: null,
    sentimentDiscountCode: null,
    brandName: "Dyson",
    totalShares: "50000.00",
    availableShares: "50000.00",
    initialSharePrice: "5.00",
    isAdflowPromoted: true,
    adflowExpiresAt: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000),
    hasDividendBadge: false,
    dividendStreakDays: 0,
    createdAt: new Date("2024-04-01"),
    updatedAt: new Date(),
  },
  {
    id: 7,
    name: "Spotify Premium",
    ticker: "SPOT",
    description: "Music streaming service",
    category: "Entertainment",
    imageUrl: null,
    ownerId: 1,
    currentPrice: "8.45",
    previousPrice: "8.32",
    priceChange: "0.13",
    priceChangePercent: "1.56",
    totalRatings: 1876,
    status: "active",
    itemType: "service",
    isInNpbNsb: false,
    npbNsbExpiresAt: null,
    purchaseUrl: null,
    externalPageUrl: null,
    sentimentDiscount: "3 Months Free",
    sentimentDiscountCode: "SPOT3",
    brandName: "Spotify",
    totalShares: "1000000.00",
    availableShares: "800000.00",
    initialSharePrice: "5.00",
    isAdflowPromoted: false,
    adflowExpiresAt: null,
    hasDividendBadge: true,
    dividendStreakDays: 52,
    createdAt: new Date("2023-12-01"),
    updatedAt: new Date(),
  },
  {
    id: 8,
    name: "Lululemon Align Pants",
    ticker: "LULU",
    description: "Premium athletic wear",
    category: "Fashion",
    imageUrl: null,
    ownerId: 1,
    currentPrice: "8.92",
    previousPrice: "8.78",
    priceChange: "0.14",
    priceChangePercent: "1.59",
    totalRatings: 1234,
    status: "active",
    itemType: "product",
    isInNpbNsb: false,
    npbNsbExpiresAt: null,
    purchaseUrl: null,
    externalPageUrl: null,
    sentimentDiscount: null,
    sentimentDiscountCode: null,
    brandName: "Lululemon",
    totalShares: "300000.00",
    availableShares: "250000.00",
    initialSharePrice: "5.00",
    isAdflowPromoted: false,
    adflowExpiresAt: null,
    hasDividendBadge: true,
    dividendStreakDays: 41,
    createdAt: new Date("2024-01-10"),
    updatedAt: new Date(),
  },
];

// Mock recent ratings/statements
export const mockRecentStatements: Array<{
  id: number;
  productTicker: string;
  productName: string;
  statement: string;
  score: number;
  countryCode: string;
  createdAt: Date;
}> = [
  {
    id: 1,
    productTicker: "AAPL",
    productName: "Apple iPhone 16",
    statement: "Best camera I've ever used on any phone",
    score: 9,
    countryCode: "US",
    createdAt: new Date(Date.now() - 2 * 60 * 1000),
  },
  {
    id: 2,
    productTicker: "TSLA",
    productName: "Tesla Model S",
    statement: "Autopilot needs work but love the acceleration",
    score: 7,
    countryCode: "DE",
    createdAt: new Date(Date.now() - 5 * 60 * 1000),
  },
  {
    id: 3,
    productTicker: "SNY",
    productName: "Sony PlayStation 5",
    statement: "Finally got one and it's absolutely incredible",
    score: 10,
    countryCode: "JP",
    createdAt: new Date(Date.now() - 8 * 60 * 1000),
  },
  {
    id: 4,
    productTicker: "NKE",
    productName: "Nike Air Max",
    statement: "Comfortable but overpriced for what you get",
    score: 6,
    countryCode: "GB",
    createdAt: new Date(Date.now() - 12 * 60 * 1000),
  },
  {
    id: 5,
    productTicker: "SPOT",
    productName: "Spotify Premium",
    statement: "Discover Weekly keeps getting better every week",
    score: 9,
    countryCode: "SE",
    createdAt: new Date(Date.now() - 15 * 60 * 1000),
  },
];

// Mock price history for charts
export const mockPriceHistory: Record<string, Array<{ price: number; time: Date }>> = {
  AAPL: Array.from({ length: 30 }, (_, i) => ({
    price: 8.2 + Math.sin(i / 5) * 0.5 + Math.random() * 0.3,
    time: new Date(Date.now() - (30 - i) * 24 * 60 * 60 * 1000),
  })),
  TSLA: Array.from({ length: 30 }, (_, i) => ({
    price: 7.5 - Math.cos(i / 4) * 0.4 + Math.random() * 0.2,
    time: new Date(Date.now() - (30 - i) * 24 * 60 * 60 * 1000),
  })),
  SNY: Array.from({ length: 30 }, (_, i) => ({
    price: 8.8 + (i / 30) * 0.4 + Math.random() * 0.2,
    time: new Date(Date.now() - (30 - i) * 24 * 60 * 60 * 1000),
  })),
};

// Country data for heat map
export const countryData: Record<
  string,
  { name: string; code: string; avgScore?: number; totalRatings?: number }
> = {
  US: { name: "United States", code: "US", avgScore: 8.2, totalRatings: 4521 },
  GB: { name: "United Kingdom", code: "GB", avgScore: 7.8, totalRatings: 1234 },
  DE: { name: "Germany", code: "DE", avgScore: 7.5, totalRatings: 987 },
  JP: { name: "Japan", code: "JP", avgScore: 8.9, totalRatings: 2341 },
  FR: { name: "France", code: "FR", avgScore: 7.2, totalRatings: 654 },
  CA: { name: "Canada", code: "CA", avgScore: 8.1, totalRatings: 876 },
  AU: { name: "Australia", code: "AU", avgScore: 7.9, totalRatings: 543 },
  BR: { name: "Brazil", code: "BR", avgScore: 7.6, totalRatings: 432 },
  IN: { name: "India", code: "IN", avgScore: 8.4, totalRatings: 1876 },
  KR: { name: "South Korea", code: "KR", avgScore: 8.7, totalRatings: 1543 },
};

// Categories for filtering
export const categories = [
  "All",
  "Electronics",
  "Automotive",
  "Fashion",
  "Food & Beverage",
  "Gaming",
  "Home",
  "Entertainment",
  "Health",
  "Travel",
];
