import Script from "next/script";
import { Zap } from "lucide-react";

export default function Home() {
  // Demo Product ID for testing the widget
  const demoProductId = "5ca6dd48-7359-4221-9065-aba57099f696";

  return (
    <div className="flex min-h-screen flex-col bg-zinc-50 font-sans dark:bg-black text-black dark:text-zinc-50">
      <header className="flex w-full items-center justify-between p-6 border-b border-zinc-200 dark:border-zinc-800 backdrop-blur-md sticky top-0 bg-white/70 dark:bg-black/70 z-10">
        <div className="flex items-center gap-2 text-indigo-600 dark:text-indigo-400">
          <Zap className="h-6 w-6 fill-current" />
          <span className="text-xl font-bold tracking-tight text-zinc-900 dark:text-zinc-50">Prodomatix</span>
        </div>
        <nav className="flex gap-6">
          <a href="/docs" className="text-sm font-medium hover:text-zinc-500 transition-colors">Documentation</a>
          <a href="/dashboard" className="text-sm font-medium hover:text-zinc-500 transition-colors">Dashboard</a>
        </nav>
      </header>

      <main className="flex-1 flex flex-col items-center py-16 px-6">
        <section className="max-w-4xl w-full text-center mb-16">
          <h1 className="text-5xl md:text-6xl font-extrabold mb-6 bg-gradient-to-r from-black via-zinc-600 to-black dark:from-white dark:via-zinc-400 dark:to-white bg-clip-text text-transparent italic">
            Reviews at the Speed of Commerce.
          </h1>
          <p className="text-xl text-zinc-600 dark:text-zinc-400 mb-10 max-w-2xl mx-auto">
            The headless review engine for modern brands. Syndicate feedback, 
            gain AI-driven insights, and boost conversions across every retail channel.
          </p>
          <div className="flex flex-wrap justify-center gap-4">
            <button className="px-8 py-3 bg-black dark:bg-white text-white dark:text-black rounded-full font-semibold hover:opacity-90 transition-opacity">
              Get Started
            </button>
            <a href="/docs" className="px-8 py-3 border border-zinc-300 dark:border-zinc-700 rounded-full font-semibold hover:bg-zinc-100 dark:hover:bg-zinc-900 transition-colors">
              Read API Docs
            </a>
          </div>
        </section>

        <section className="grid grid-cols-1 md:grid-cols-3 gap-8 max-w-6xl w-full mb-20 px-4">
          <div className="p-8 rounded-2xl bg-white dark:bg-zinc-900 border border-zinc-200 dark:border-zinc-800">
            <h3 className="text-2xl font-bold mb-4">🤖 AI-Native</h3>
            <p className="text-zinc-600 dark:text-zinc-400">
              Automatic rating mismatch detection (&quot;5 stars but terrible text&quot;).
              Instant &quot;Pros & Cons&quot; summaries generated by LLMs.
            </p>
          </div>
          <div className="p-8 rounded-2xl bg-white dark:bg-zinc-900 border border-zinc-200 dark:border-zinc-800">
            <h3 className="text-2xl font-bold mb-4">📡 Syndication</h3>
            <p className="text-zinc-600 dark:text-zinc-400">
              Push your approved reviews to 50+ retail partners instantly via our secure API.
              One source of truth for all your user feedback.
            </p>
          </div>
          <div className="p-8 rounded-2xl bg-white dark:bg-zinc-900 border border-zinc-200 dark:border-zinc-800">
            <h3 className="text-2xl font-bold mb-4">💎 Enterprise Ready</h3>
            <p className="text-zinc-600 dark:text-zinc-400">
              SaaS-ready architecture with tiered subscriptions, visual review support (Video/Photo),
              and verified buyer badges.
            </p>
          </div>
        </section>

        <section className="w-full max-w-xl p-8 rounded-3xl bg-white dark:bg-zinc-900 shadow-2xl border border-zinc-200 dark:border-zinc-800">
          <h2 className="text-2xl font-bold mb-6 text-center">Widget Preview</h2>
          <div 
            id="prodomatix-reviews" 
            data-product-id={demoProductId}
            className="min-h-[400px]"
          >
            {/* The widget will be injected here */}
            <div className="flex flex-col items-center justify-center p-12 text-zinc-400">
              <div className="w-8 h-8 border-4 border-zinc-200 border-t-black rounded-full animate-spin mb-4"></div>
              <p>Loading Review Widget...</p>
            </div>
          </div>
        </section>
      </main>

      <footer className="w-full p-12 border-t border-zinc-200 dark:border-zinc-800 bg-white dark:bg-black">
        <div className="max-w-6xl mx-auto flex flex-col md:flex-row justify-between items-center gap-8">
          <div className="flex items-center gap-2 text-indigo-600 dark:text-indigo-400">
            <Zap className="h-5 w-5 fill-current" />
            <span className="font-bold tracking-tight text-zinc-900 dark:text-zinc-50">Prodomatix</span>
            <span className="text-zinc-400 ml-2">© 2026</span>
          </div>
          
          <div className="flex flex-wrap justify-center gap-6 text-sm font-medium text-zinc-500">
            <a href="/terms" className="hover:text-zinc-900 dark:hover:text-white transition-colors">Terms of Service</a>
            <a href="/privacy" className="hover:text-zinc-900 dark:hover:text-white transition-colors">Privacy Policy</a>
            <a href="/integrity" className="hover:text-zinc-900 dark:hover:text-white transition-colors">Review Integrity</a>
            <a href="/docs" className="hover:text-zinc-900 dark:hover:text-white transition-colors">API Reference</a>
          </div>

          <div className="text-zinc-400 text-xs">
            Built for the future of e-commerce.
          </div>
        </div>
      </footer>

      {/* Inject the Prodomatix Widget */}
      <Script src="/widget.js" strategy="afterInteractive" />
    </div>
  );
}
